//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionsTBL
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> loginDateTime { get; set; }
        public Nullable<System.DateTime> logoutDateTime { get; set; }
    
        public virtual UserTBL UserTBL { get; set; }
    }
}
